//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace SonicAPI.RESTSchema
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    [XmlRoot("subsonic-response", Namespace = "http://subsonic.org/restapi", IsNullable = false)]
    public partial class Response
    {

        private object itemField;

        private ItemChoiceType itemElementNameField;

        private ResponseStatus statusField;

        private string versionField;

        /// <remarks/>
        [XmlElement("album", typeof(AlbumWithSongsID3))]
        [XmlElement("albumList", typeof(AlbumList))]
        [XmlElement("albumList2", typeof(AlbumList2))]
        [XmlElement("artist", typeof(ArtistWithAlbumsID3))]
        [XmlElement("artists", typeof(ArtistsID3))]
        [XmlElement("chatMessages", typeof(ChatMessages))]
        [XmlElement("directory", typeof(Directory))]
        [XmlElement("error", typeof(Error))]
        [XmlElement("indexes", typeof(Indexes))]
        [XmlElement("jukeboxPlaylist", typeof(JukeboxPlaylist))]
        [XmlElement("jukeboxStatus", typeof(JukeboxStatus))]
        [XmlElement("license", typeof(License))]
        [XmlElement("lyrics", typeof(Lyrics))]
        [XmlElement("musicFolders", typeof(MusicFolders))]
        [XmlElement("nowPlaying", typeof(NowPlaying))]
        [XmlElement("playlist", typeof(PlaylistWithSongs))]
        [XmlElement("playlists", typeof(Playlists))]
        [XmlElement("podcasts", typeof(Podcasts))]
        [XmlElement("randomSongs", typeof(RandomSongs))]
        [XmlElement("searchResult", typeof(SearchResult))]
        [XmlElement("searchResult2", typeof(SearchResult2))]
        [XmlElement("searchResult3", typeof(SearchResult3))]
        [XmlElement("shares", typeof(Shares))]
        [XmlElement("song", typeof(Child))]
        [XmlElement("starred", typeof(Starred))]
        [XmlElement("starred2", typeof(Starred2))]
        [XmlElement("user", typeof(User))]
        [XmlElement("users", typeof(Users))]
        [XmlElement("videos", typeof(Videos))]
        [XmlChoiceIdentifier("ItemElementName")]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public ResponseStatus status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class AlbumWithSongsID3 : AlbumID3
    {

        private Child[] songField;

        /// <remarks/>
        [XmlElement("song")]
        public Child[] song
        {
            get
            {
                return this.songField;
            }
            set
            {
                this.songField = value;
            }
        }
    }

    /// <remarks/>
    [XmlInclude(typeof(PodcastEpisode))]
    [XmlInclude(typeof(NowPlayingEntry))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class Child
    {

        private string idField;

        private string parentField;

        private bool isDirField;

        private string titleField;

        private string albumField;

        private string artistField;

        private int trackField;

        private bool trackFieldSpecified;

        private int yearField;

        private bool yearFieldSpecified;

        private string genreField;

        private string coverArtField;

        private long sizeField;

        private bool sizeFieldSpecified;

        private string contentTypeField;

        private string suffixField;

        private string transcodedContentTypeField;

        private string transcodedSuffixField;

        private int durationField;

        private bool durationFieldSpecified;

        private int bitRateField;

        private bool bitRateFieldSpecified;

        private string pathField;

        private bool isVideoField;

        private bool isVideoFieldSpecified;

        private int userRatingField;

        private bool userRatingFieldSpecified;

        private double averageRatingField;

        private bool averageRatingFieldSpecified;

        private int discNumberField;

        private bool discNumberFieldSpecified;

        private System.DateTime createdField;

        private bool createdFieldSpecified;

        private System.DateTime starredField;

        private bool starredFieldSpecified;

        private string albumIdField;

        private string artistIdField;

        private MediaType typeField;

        private bool typeFieldSpecified;

        /// <remarks/>
        [XmlAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string parent
        {
            get
            {
                return this.parentField;
            }
            set
            {
                this.parentField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public bool isDir
        {
            get
            {
                return this.isDirField;
            }
            set
            {
                this.isDirField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string album
        {
            get
            {
                return this.albumField;
            }
            set
            {
                this.albumField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string artist
        {
            get
            {
                return this.artistField;
            }
            set
            {
                this.artistField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public int track
        {
            get
            {
                return this.trackField;
            }
            set
            {
                this.trackField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool trackSpecified
        {
            get
            {
                return this.trackFieldSpecified;
            }
            set
            {
                this.trackFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public int year
        {
            get
            {
                return this.yearField;
            }
            set
            {
                this.yearField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool yearSpecified
        {
            get
            {
                return this.yearFieldSpecified;
            }
            set
            {
                this.yearFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string genre
        {
            get
            {
                return this.genreField;
            }
            set
            {
                this.genreField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string coverArt
        {
            get
            {
                return this.coverArtField;
            }
            set
            {
                this.coverArtField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public long size
        {
            get
            {
                return this.sizeField;
            }
            set
            {
                this.sizeField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool sizeSpecified
        {
            get
            {
                return this.sizeFieldSpecified;
            }
            set
            {
                this.sizeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string contentType
        {
            get
            {
                return this.contentTypeField;
            }
            set
            {
                this.contentTypeField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string suffix
        {
            get
            {
                return this.suffixField;
            }
            set
            {
                this.suffixField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string transcodedContentType
        {
            get
            {
                return this.transcodedContentTypeField;
            }
            set
            {
                this.transcodedContentTypeField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string transcodedSuffix
        {
            get
            {
                return this.transcodedSuffixField;
            }
            set
            {
                this.transcodedSuffixField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public int duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool durationSpecified
        {
            get
            {
                return this.durationFieldSpecified;
            }
            set
            {
                this.durationFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public int bitRate
        {
            get
            {
                return this.bitRateField;
            }
            set
            {
                this.bitRateField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool bitRateSpecified
        {
            get
            {
                return this.bitRateFieldSpecified;
            }
            set
            {
                this.bitRateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public bool isVideo
        {
            get
            {
                return this.isVideoField;
            }
            set
            {
                this.isVideoField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool isVideoSpecified
        {
            get
            {
                return this.isVideoFieldSpecified;
            }
            set
            {
                this.isVideoFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public int userRating
        {
            get
            {
                return this.userRatingField;
            }
            set
            {
                this.userRatingField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool userRatingSpecified
        {
            get
            {
                return this.userRatingFieldSpecified;
            }
            set
            {
                this.userRatingFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public double averageRating
        {
            get
            {
                return this.averageRatingField;
            }
            set
            {
                this.averageRatingField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool averageRatingSpecified
        {
            get
            {
                return this.averageRatingFieldSpecified;
            }
            set
            {
                this.averageRatingFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public int discNumber
        {
            get
            {
                return this.discNumberField;
            }
            set
            {
                this.discNumberField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool discNumberSpecified
        {
            get
            {
                return this.discNumberFieldSpecified;
            }
            set
            {
                this.discNumberFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public System.DateTime created
        {
            get
            {
                return this.createdField;
            }
            set
            {
                this.createdField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool createdSpecified
        {
            get
            {
                return this.createdFieldSpecified;
            }
            set
            {
                this.createdFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public System.DateTime starred
        {
            get
            {
                return this.starredField;
            }
            set
            {
                this.starredField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool starredSpecified
        {
            get
            {
                return this.starredFieldSpecified;
            }
            set
            {
                this.starredFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string albumId
        {
            get
            {
                return this.albumIdField;
            }
            set
            {
                this.albumIdField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string artistId
        {
            get
            {
                return this.artistIdField;
            }
            set
            {
                this.artistIdField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public MediaType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool typeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public enum MediaType
    {

        /// <remarks/>
        music,

        /// <remarks/>
        podcast,

        /// <remarks/>
        audiobook,

        /// <remarks/>
        video,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class Error
    {

        private int codeField;

        private string messageField;

        /// <remarks/>
        [XmlAttribute()]
        public int code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class Starred2
    {

        private ArtistID3[] artistField;

        private AlbumID3[] albumField;

        private Child[] songField;

        /// <remarks/>
        [XmlElement("artist")]
        public ArtistID3[] artist
        {
            get
            {
                return this.artistField;
            }
            set
            {
                this.artistField = value;
            }
        }

        /// <remarks/>
        [XmlElement("album")]
        public AlbumID3[] album
        {
            get
            {
                return this.albumField;
            }
            set
            {
                this.albumField = value;
            }
        }

        /// <remarks/>
        [XmlElement("song")]
        public Child[] song
        {
            get
            {
                return this.songField;
            }
            set
            {
                this.songField = value;
            }
        }
    }

    /// <remarks/>
    [XmlInclude(typeof(ArtistWithAlbumsID3))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class ArtistID3
    {

        private string idField;

        private string nameField;

        private string coverArtField;

        private int albumCountField;

        private System.DateTime starredField;

        private bool starredFieldSpecified;

        /// <remarks/>
        [XmlAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string coverArt
        {
            get
            {
                return this.coverArtField;
            }
            set
            {
                this.coverArtField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public int albumCount
        {
            get
            {
                return this.albumCountField;
            }
            set
            {
                this.albumCountField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public System.DateTime starred
        {
            get
            {
                return this.starredField;
            }
            set
            {
                this.starredField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool starredSpecified
        {
            get
            {
                return this.starredFieldSpecified;
            }
            set
            {
                this.starredFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class ArtistWithAlbumsID3 : ArtistID3
    {

        private AlbumID3[] albumField;

        /// <remarks/>
        [XmlElement("album")]
        public AlbumID3[] album
        {
            get
            {
                return this.albumField;
            }
            set
            {
                this.albumField = value;
            }
        }
    }

    /// <remarks/>
    [XmlInclude(typeof(AlbumWithSongsID3))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class AlbumID3
    {

        private string idField;

        private string nameField;

        private string artistField;

        private string artistIdField;

        private string coverArtField;

        private int songCountField;

        private int durationField;

        private System.DateTime createdField;

        private System.DateTime starredField;

        private bool starredFieldSpecified;

        /// <remarks/>
        [XmlAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string artist
        {
            get
            {
                return this.artistField;
            }
            set
            {
                this.artistField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string artistId
        {
            get
            {
                return this.artistIdField;
            }
            set
            {
                this.artistIdField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string coverArt
        {
            get
            {
                return this.coverArtField;
            }
            set
            {
                this.coverArtField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public int songCount
        {
            get
            {
                return this.songCountField;
            }
            set
            {
                this.songCountField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public int duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public System.DateTime created
        {
            get
            {
                return this.createdField;
            }
            set
            {
                this.createdField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public System.DateTime starred
        {
            get
            {
                return this.starredField;
            }
            set
            {
                this.starredField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool starredSpecified
        {
            get
            {
                return this.starredFieldSpecified;
            }
            set
            {
                this.starredFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class Starred
    {

        private Artist[] artistField;

        private Child[] albumField;

        private Child[] songField;

        /// <remarks/>
        [XmlElement("artist")]
        public Artist[] artist
        {
            get
            {
                return this.artistField;
            }
            set
            {
                this.artistField = value;
            }
        }

        /// <remarks/>
        [XmlElement("album")]
        public Child[] album
        {
            get
            {
                return this.albumField;
            }
            set
            {
                this.albumField = value;
            }
        }

        /// <remarks/>
        [XmlElement("song")]
        public Child[] song
        {
            get
            {
                return this.songField;
            }
            set
            {
                this.songField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class Artist
    {

        private string idField;

        private string nameField;

        /// <remarks/>
        [XmlAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class Shares
    {

        private Share[] shareField;

        /// <remarks/>
        [XmlElement("share")]
        public Share[] share
        {
            get
            {
                return this.shareField;
            }
            set
            {
                this.shareField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class Share
    {

        private Child[] entryField;

        private string idField;

        private string urlField;

        private string descriptionField;

        private string usernameField;

        private System.DateTime createdField;

        private System.DateTime expiresField;

        private bool expiresFieldSpecified;

        private System.DateTime lastVisitedField;

        private bool lastVisitedFieldSpecified;

        private int visitCountField;

        /// <remarks/>
        [XmlElement("entry")]
        public Child[] entry
        {
            get
            {
                return this.entryField;
            }
            set
            {
                this.entryField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public System.DateTime created
        {
            get
            {
                return this.createdField;
            }
            set
            {
                this.createdField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public System.DateTime expires
        {
            get
            {
                return this.expiresField;
            }
            set
            {
                this.expiresField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool expiresSpecified
        {
            get
            {
                return this.expiresFieldSpecified;
            }
            set
            {
                this.expiresFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public System.DateTime lastVisited
        {
            get
            {
                return this.lastVisitedField;
            }
            set
            {
                this.lastVisitedField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool lastVisitedSpecified
        {
            get
            {
                return this.lastVisitedFieldSpecified;
            }
            set
            {
                this.lastVisitedFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public int visitCount
        {
            get
            {
                return this.visitCountField;
            }
            set
            {
                this.visitCountField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class Podcasts
    {

        private PodcastChannel[] channelField;

        /// <remarks/>
        [XmlElement("channel")]
        public PodcastChannel[] channel
        {
            get
            {
                return this.channelField;
            }
            set
            {
                this.channelField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class PodcastChannel
    {

        private PodcastEpisode[] episodeField;

        private string idField;

        private string urlField;

        private string titleField;

        private string descriptionField;

        private PodcastStatus statusField;

        private string errorMessageField;

        /// <remarks/>
        [XmlElement("episode")]
        public PodcastEpisode[] episode
        {
            get
            {
                return this.episodeField;
            }
            set
            {
                this.episodeField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public PodcastStatus status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class PodcastEpisode : Child
    {

        private string streamIdField;

        private string descriptionField;

        private PodcastStatus statusField;

        private System.DateTime publishDateField;

        private bool publishDateFieldSpecified;

        /// <remarks/>
        [XmlAttribute()]
        public string streamId
        {
            get
            {
                return this.streamIdField;
            }
            set
            {
                this.streamIdField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public PodcastStatus status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public System.DateTime publishDate
        {
            get
            {
                return this.publishDateField;
            }
            set
            {
                this.publishDateField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool publishDateSpecified
        {
            get
            {
                return this.publishDateFieldSpecified;
            }
            set
            {
                this.publishDateFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public enum PodcastStatus
    {

        /// <remarks/>
        @new,

        /// <remarks/>
        downloading,

        /// <remarks/>
        completed,

        /// <remarks/>
        error,

        /// <remarks/>
        deleted,

        /// <remarks/>
        skipped,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class Lyrics
    {

        private string artistField;

        private string titleField;

        private string[] textField;

        /// <remarks/>
        [XmlAttribute()]
        public string artist
        {
            get
            {
                return this.artistField;
            }
            set
            {
                this.artistField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        [XmlText()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class RandomSongs
    {

        private Child[] songField;

        /// <remarks/>
        [XmlElement("song")]
        public Child[] song
        {
            get
            {
                return this.songField;
            }
            set
            {
                this.songField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class AlbumList2
    {

        private AlbumID3[] albumField;

        /// <remarks/>
        [XmlElement("album")]
        public AlbumID3[] album
        {
            get
            {
                return this.albumField;
            }
            set
            {
                this.albumField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class AlbumList
    {

        private Child[] albumField;

        /// <remarks/>
        [XmlElement("album")]
        public Child[] album
        {
            get
            {
                return this.albumField;
            }
            set
            {
                this.albumField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class ChatMessages
    {

        private ChatMessage[] chatMessageField;

        /// <remarks/>
        [XmlElement("chatMessage")]
        public ChatMessage[] chatMessage
        {
            get
            {
                return this.chatMessageField;
            }
            set
            {
                this.chatMessageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class ChatMessage
    {

        private string usernameField;

        private long timeField;

        private string messageField;

        /// <remarks/>
        [XmlAttribute()]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public long time
        {
            get
            {
                return this.timeField;
            }
            set
            {
                this.timeField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class Users
    {

        private User[] userField;

        /// <remarks/>
        [XmlElement("user")]
        public User[] user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class User
    {

        private string usernameField;

        private string emailField;

        private bool scrobblingEnabledField;

        private bool adminRoleField;

        private bool settingsRoleField;

        private bool downloadRoleField;

        private bool uploadRoleField;

        private bool playlistRoleField;

        private bool coverArtRoleField;

        private bool commentRoleField;

        private bool podcastRoleField;

        private bool streamRoleField;

        private bool jukeboxRoleField;

        private bool shareRoleField;

        /// <remarks/>
        [XmlAttribute()]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public bool scrobblingEnabled
        {
            get
            {
                return this.scrobblingEnabledField;
            }
            set
            {
                this.scrobblingEnabledField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public bool adminRole
        {
            get
            {
                return this.adminRoleField;
            }
            set
            {
                this.adminRoleField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public bool settingsRole
        {
            get
            {
                return this.settingsRoleField;
            }
            set
            {
                this.settingsRoleField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public bool downloadRole
        {
            get
            {
                return this.downloadRoleField;
            }
            set
            {
                this.downloadRoleField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public bool uploadRole
        {
            get
            {
                return this.uploadRoleField;
            }
            set
            {
                this.uploadRoleField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public bool playlistRole
        {
            get
            {
                return this.playlistRoleField;
            }
            set
            {
                this.playlistRoleField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public bool coverArtRole
        {
            get
            {
                return this.coverArtRoleField;
            }
            set
            {
                this.coverArtRoleField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public bool commentRole
        {
            get
            {
                return this.commentRoleField;
            }
            set
            {
                this.commentRoleField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public bool podcastRole
        {
            get
            {
                return this.podcastRoleField;
            }
            set
            {
                this.podcastRoleField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public bool streamRole
        {
            get
            {
                return this.streamRoleField;
            }
            set
            {
                this.streamRoleField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public bool jukeboxRole
        {
            get
            {
                return this.jukeboxRoleField;
            }
            set
            {
                this.jukeboxRoleField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public bool shareRole
        {
            get
            {
                return this.shareRoleField;
            }
            set
            {
                this.shareRoleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class License
    {

        private bool validField;

        private string emailField;

        private string keyField;

        private System.DateTime dateField;

        private bool dateFieldSpecified;

        /// <remarks/>
        [XmlAttribute()]
        public bool valid
        {
            get
            {
                return this.validField;
            }
            set
            {
                this.validField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public System.DateTime date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool dateSpecified
        {
            get
            {
                return this.dateFieldSpecified;
            }
            set
            {
                this.dateFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [XmlInclude(typeof(JukeboxPlaylist))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class JukeboxStatus
    {

        private int currentIndexField;

        private bool playingField;

        private float gainField;

        private int positionField;

        private bool positionFieldSpecified;

        /// <remarks/>
        [XmlAttribute()]
        public int currentIndex
        {
            get
            {
                return this.currentIndexField;
            }
            set
            {
                this.currentIndexField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public bool playing
        {
            get
            {
                return this.playingField;
            }
            set
            {
                this.playingField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public float gain
        {
            get
            {
                return this.gainField;
            }
            set
            {
                this.gainField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public int position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool positionSpecified
        {
            get
            {
                return this.positionFieldSpecified;
            }
            set
            {
                this.positionFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class JukeboxPlaylist : JukeboxStatus
    {

        private Child[] entryField;

        /// <remarks/>
        [XmlElement("entry")]
        public Child[] entry
        {
            get
            {
                return this.entryField;
            }
            set
            {
                this.entryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class Playlists
    {

        private Playlist[] playlistField;

        /// <remarks/>
        [XmlElement("playlist")]
        public Playlist[] playlist
        {
            get
            {
                return this.playlistField;
            }
            set
            {
                this.playlistField = value;
            }
        }
    }

    /// <remarks/>
    [XmlInclude(typeof(PlaylistWithSongs))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class Playlist
    {

        private string[] allowedUserField;

        private string idField;

        private string nameField;

        private string commentField;

        private string ownerField;

        private bool publicField;

        private bool publicFieldSpecified;

        private int songCountField;

        private int durationField;

        private System.DateTime createdField;

        /// <remarks/>
        [XmlElement("allowedUser")]
        public string[] allowedUser
        {
            get
            {
                return this.allowedUserField;
            }
            set
            {
                this.allowedUserField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string owner
        {
            get
            {
                return this.ownerField;
            }
            set
            {
                this.ownerField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public bool @public
        {
            get
            {
                return this.publicField;
            }
            set
            {
                this.publicField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool publicSpecified
        {
            get
            {
                return this.publicFieldSpecified;
            }
            set
            {
                this.publicFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public int songCount
        {
            get
            {
                return this.songCountField;
            }
            set
            {
                this.songCountField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public int duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public System.DateTime created
        {
            get
            {
                return this.createdField;
            }
            set
            {
                this.createdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class PlaylistWithSongs : Playlist
    {

        private Child[] entryField;

        /// <remarks/>
        [XmlElement("entry")]
        public Child[] entry
        {
            get
            {
                return this.entryField;
            }
            set
            {
                this.entryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class SearchResult3
    {

        private ArtistID3[] artistField;

        private AlbumID3[] albumField;

        private Child[] songField;

        /// <remarks/>
        [XmlElement("artist")]
        public ArtistID3[] artist
        {
            get
            {
                return this.artistField;
            }
            set
            {
                this.artistField = value;
            }
        }

        /// <remarks/>
        [XmlElement("album")]
        public AlbumID3[] album
        {
            get
            {
                return this.albumField;
            }
            set
            {
                this.albumField = value;
            }
        }

        /// <remarks/>
        [XmlElement("song")]
        public Child[] song
        {
            get
            {
                return this.songField;
            }
            set
            {
                this.songField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class SearchResult2
    {

        private Artist[] artistField;

        private Child[] albumField;

        private Child[] songField;

        /// <remarks/>
        [XmlElement("artist")]
        public Artist[] artist
        {
            get
            {
                return this.artistField;
            }
            set
            {
                this.artistField = value;
            }
        }

        /// <remarks/>
        [XmlElement("album")]
        public Child[] album
        {
            get
            {
                return this.albumField;
            }
            set
            {
                this.albumField = value;
            }
        }

        /// <remarks/>
        [XmlElement("song")]
        public Child[] song
        {
            get
            {
                return this.songField;
            }
            set
            {
                this.songField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class SearchResult
    {

        private Child[] matchField;

        private int offsetField;

        private int totalHitsField;

        /// <remarks/>
        [XmlElement("match")]
        public Child[] match
        {
            get
            {
                return this.matchField;
            }
            set
            {
                this.matchField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public int offset
        {
            get
            {
                return this.offsetField;
            }
            set
            {
                this.offsetField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public int totalHits
        {
            get
            {
                return this.totalHitsField;
            }
            set
            {
                this.totalHitsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class NowPlaying
    {

        private NowPlayingEntry[] entryField;

        /// <remarks/>
        [XmlElement("entry")]
        public NowPlayingEntry[] entry
        {
            get
            {
                return this.entryField;
            }
            set
            {
                this.entryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class NowPlayingEntry : Child
    {

        private string usernameField;

        private int minutesAgoField;

        private int playerIdField;

        private string playerNameField;

        /// <remarks/>
        [XmlAttribute()]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public int minutesAgo
        {
            get
            {
                return this.minutesAgoField;
            }
            set
            {
                this.minutesAgoField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public int playerId
        {
            get
            {
                return this.playerIdField;
            }
            set
            {
                this.playerIdField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string playerName
        {
            get
            {
                return this.playerNameField;
            }
            set
            {
                this.playerNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class Videos
    {

        private Child[] videoField;

        /// <remarks/>
        [XmlElement("video")]
        public Child[] video
        {
            get
            {
                return this.videoField;
            }
            set
            {
                this.videoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class ArtistsID3
    {

        private IndexID3[] indexField;

        /// <remarks/>
        [XmlElement("index")]
        public IndexID3[] index
        {
            get
            {
                return this.indexField;
            }
            set
            {
                this.indexField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class IndexID3
    {

        private ArtistID3[] artistField;

        private string nameField;

        /// <remarks/>
        [XmlElement("artist")]
        public ArtistID3[] artist
        {
            get
            {
                return this.artistField;
            }
            set
            {
                this.artistField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class Directory
    {

        private Child[] childField;

        private string idField;

        private string parentField;

        private string nameField;

        /// <remarks/>
        [XmlElement("child")]
        public Child[] child
        {
            get
            {
                return this.childField;
            }
            set
            {
                this.childField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string parent
        {
            get
            {
                return this.parentField;
            }
            set
            {
                this.parentField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class Index
    {

        private Artist[] artistField;

        private string nameField;

        /// <remarks/>
        [XmlElement("artist")]
        public Artist[] artist
        {
            get
            {
                return this.artistField;
            }
            set
            {
                this.artistField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class Indexes
    {

        private Artist[] shortcutField;

        private Index[] indexField;

        private Child[] childField;

        private long lastModifiedField;

        /// <remarks/>
        [XmlElement("shortcut")]
        public Artist[] shortcut
        {
            get
            {
                return this.shortcutField;
            }
            set
            {
                this.shortcutField = value;
            }
        }

        /// <remarks/>
        [XmlElement("index")]
        public Index[] index
        {
            get
            {
                return this.indexField;
            }
            set
            {
                this.indexField = value;
            }
        }

        /// <remarks/>
        [XmlElement("child")]
        public Child[] child
        {
            get
            {
                return this.childField;
            }
            set
            {
                this.childField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public long lastModified
        {
            get
            {
                return this.lastModifiedField;
            }
            set
            {
                this.lastModifiedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class MusicFolders
    {

        private MusicFolder[] musicFolderField;

        /// <remarks/>
        [XmlElement("musicFolder")]
        public MusicFolder[] musicFolder
        {
            get
            {
                return this.musicFolderField;
            }
            set
            {
                this.musicFolderField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public partial class MusicFolder
    {

        private int idField;

        private string nameField;

        /// <remarks/>
        [XmlAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [XmlType(Namespace = "http://subsonic.org/restapi", IncludeInSchema = false)]
    public enum ItemChoiceType
    {

        /// <remarks/>
        album,

        /// <remarks/>
        albumList,

        /// <remarks/>
        albumList2,

        /// <remarks/>
        artist,

        /// <remarks/>
        artists,

        /// <remarks/>
        chatMessages,

        /// <remarks/>
        directory,

        /// <remarks/>
        error,

        /// <remarks/>
        indexes,

        /// <remarks/>
        jukeboxPlaylist,

        /// <remarks/>
        jukeboxStatus,

        /// <remarks/>
        license,

        /// <remarks/>
        lyrics,

        /// <remarks/>
        musicFolders,

        /// <remarks/>
        nowPlaying,

        /// <remarks/>
        playlist,

        /// <remarks/>
        playlists,

        /// <remarks/>
        podcasts,

        /// <remarks/>
        randomSongs,

        /// <remarks/>
        searchResult,

        /// <remarks/>
        searchResult2,

        /// <remarks/>
        searchResult3,

        /// <remarks/>
        shares,

        /// <remarks/>
        song,

        /// <remarks/>
        starred,

        /// <remarks/>
        starred2,

        /// <remarks/>
        user,

        /// <remarks/>
        users,

        /// <remarks/>
        videos,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [XmlType(Namespace = "http://subsonic.org/restapi")]
    public enum ResponseStatus
    {

        /// <remarks/>
        ok,

        /// <remarks/>
        failed,
    }
}
